spring:
  # Redis
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


cloud:
  aws:
    s3:
      bucket: ????
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ????
      secretKey: ????


# JWT
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN
