server:
  port : 5000
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}



cloud:
  aws:
    s3:
      bucket: 추가할것
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: 추가할것
      secretKey: 추가할것